### ISSUE TITLE
[nexus] Runtime configuration of ICE candidates

### ISSUE THREAD

**Issue by Megzo** [elixir-webrtc/apps#63]
Hi Everyone,

I'm running some experiments using the Nexus app in a Kubernetes environment. Since I'm using [STUNner](https://github.com/l7mp/stunner) (basically a Kubernetes native TURN server) I needed to add my own TURN server as an ICE candidate.
Currently I think there is no way to change the ICE config during runtime, so I needed to fork the project then build my own Docker image using a specific TURN server. This worked fine, but it would be nice to have a way to configure the ICE candidate in runtime.

The are two files containing the ICE config (for client and server):
 - `nexus/assets/js/home.js`
 -  `nexus/lib/nexus/peer.ex`
 
Usually `.js` files can be overwritten during runtime in Kubernetes using `ConfigMaps`, but this was not as obvious to do so, since the file itself is quite large, and there are also minimized and gzipped versions in the container. To that end, it would be nice if the ICE config would be in a separate `.js` file.

On the server side, I have zero experience with Elixir, so I have no idea how to use an ENV variable for this purpose (especially that TURN config requires more parameters, e.g. username and password).

If you also value in this feature, can you help me add this to Nexus (and maybe to the other projects as well)?

**Comment by sgfn** [comment]
Hi @Megzo,
We'll be more than happy to make ICE servers configurable at runtime. Server-side (`peer.ex`), this should be pretty easy and we can take care of it, however, I'm not sure I understand how exactly you mean to configure it in the client-side code.

Extracting the ICE config to a separate `.js` file can be done ofc, but the minified and gzipped versions of the frontend assets are generated while building the Docker image. In the Dockerfile, this is done using `mix assets.deploy` which is an alias for these three tasks:
* [tailwind nexus --minify](https://hexdocs.pm/tailwind/Mix.Tasks.Tailwind.html)
* [esbuild nexus --minify](https://hexdocs.pm/esbuild/Mix.Tasks.Esbuild.html)
* [phx.digest](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Digest.html)

I'm not really that familiar with frontend development as a whole, so it's hard for me to say whether it's possible to somehow overwrite assets generated in this way at runtime. If you're determined to bring this feature without having to build your own Docker image, you can look into this topic and see if anyone has tried (and succeeded) to do something like this with Phoenix before.

Would you be willing to look for a potential solution to this issue?

**Comment by Megzo** [comment]
Hi @sgfn 

Thanks for the quick replay.
Sure, I'll look into how to organiz the `.js` files to that end.
I'll get back to you, when I have the idea.

**Comment by sgfn** [comment]
With Broadcaster release `0.7.1`, ICE servers are now configurable at runtime 🎉

The new ICE env variables are:
* `ICE_SERVER_URL`: if unset, defaults to the google stun server
* `ICE_SERVER_USERNAME`
* `ICE_SERVER_CREDENTIAL`
* `ICE_TRANSPORT_POLICY`: `all` by default, can be set to `relay`

These options allow users to specify one ICE server that will be used both by WHIP/WHEP web clients and the Broadcaster server
